### ISSUE TITLE
Something went wrong while using the plugin “hide-clock”

### ISSUE THREAD

**Issue by uhlhosting** [karaggeorge/kap-hide-clock#7]
undefined

**macOS version:**    Big Sur (11)
**Kap version:**      3.3.2

```
Something went wrong while using the plugin “hide-clock”

Error: Command failed with exit code 1: defaults read com.apple.systemuiserver menuExtras
2020-11-04 17:22:52.358 defaults[55116:12262860] 
The domain/default pair of (com.apple.systemuiserver, menuExtras) does not exist
    at makeError (/execa/lib/error.js:59:11)
    at handlePromise (/execa/index.js:114:26)
    at async readDefaults (/kap-hide-clock/index.js:7:20)
    at async Object.willStartRecording (/kap-hide-clock/index.js:17:20)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:56:7
    at async Promise.all (index 5)
    at async Object.startRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:148:3)
```

**Comment by karaggeorge** [comment]
Hmm, sounds like the system defaults keys have changed in Big Sure. I don't have that OS running at this moment so I can't really debug.

Could you run this in your terminal and post the results? Might help me figure out a quick fix:
```
defaults read com.apple.systemuiserver
```

**Comment by uhlhosting** [comment]
```
{
    "last-analytics-stamp" = "626202570.198285";
}
```

**Comment by karaggeorge** [comment]
Hmm, ok so they have changed the way the system handles the menu extras. I'll have to find a different solution of macOS 11. Not sure when I'll upgrade though, so anyone already on that, feel free to test other possible solutions

**Comment by sindresorhus** [comment]
On Big Sur, there's no longer a preference to hide the clock: https://github.com/feedback-assistant/reports/issues/131
